<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworkVersion>v7.0</TargetFrameworkVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Model\User.cs" />
    <Compile Remove="ViewModel\OrdersViewModel.cs" />
    <Compile Remove="ViewModel\SecondViewModel.cs" />
    <Compile Remove="ViewModel\UserViewModel.cs" />
    <Compile Remove="View\MainWindow.xaml.cs" />
    <Compile Remove="View\OrdersView.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="View\MainWindow.xaml" />
    <Page Remove="View\OrdersView.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{3259aa49-8aa1-44d3-9025-a0b520596a8c}" />
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
